/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package com.github.braisdom.jsql;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int LPAREN = 7;
  /** RegularExpression Id. */
  int RPAREN = 8;
  /** RegularExpression Id. */
  int LBRACE = 9;
  /** RegularExpression Id. */
  int RBRACE = 10;
  /** RegularExpression Id. */
  int LBRACKET = 11;
  /** RegularExpression Id. */
  int RBRACKET = 12;
  /** RegularExpression Id. */
  int SEMICOLON = 13;
  /** RegularExpression Id. */
  int COMMA = 14;
  /** RegularExpression Id. */
  int DOT = 15;
  /** RegularExpression Id. */
  int COLON = 16;
  /** RegularExpression Id. */
  int QUOTE = 17;
  /** RegularExpression Id. */
  int STRINGVAL = 18;
  /** RegularExpression Id. */
  int DBSTRINGVAL = 19;
  /** RegularExpression Id. */
  int IMPORT = 20;
  /** RegularExpression Id. */
  int DATASET = 21;
  /** RegularExpression Id. */
  int PROJECTION = 22;
  /** RegularExpression Id. */
  int AS = 23;
  /** RegularExpression Id. */
  int DIGITS = 24;
  /** RegularExpression Id. */
  int IDENTIFIER = 25;
  /** RegularExpression Id. */
  int TYPE_NAME = 26;
  /** RegularExpression Id. */
  int BACK_QUOTED_IDENTIFIER = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<LINE_COMMENT>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "\"\\\'\"",
    "<STRINGVAL>",
    "<DBSTRINGVAL>",
    "\"import\"",
    "\"dataset\"",
    "\"projection\"",
    "\"as\"",
    "<DIGITS>",
    "<IDENTIFIER>",
    "<TYPE_NAME>",
    "<BACK_QUOTED_IDENTIFIER>",
  };

}
