package com.github.braisdom.objsql;

import com.github.braisdom.objsql.transition.ColumnTransitional;

/**
 * Describes the Java Bean who maps a row in the table.
 *
 * @param <T> the bean class
 */
public interface TableRowDescriptor<T> {

    T newInstance();

    void setAutoGeneratedPK(T bean, Object primaryKeyValue);

    String getFieldName(String columnName);

    Class getFieldType(String fieldName);

    boolean isTransitable(String fieldName);

    ColumnTransitional getColumnTransition(String fieldName);

    void setValue(T modelObject, String fieldName, Object fieldValue);

    Object getValue(T modelObject, String fieldName);
}
