/* ParserTokenManager.java */
/* Generated By:JavaCC: Do not edit this line. ParserTokenManager.java */
package com.github.braisdom.jds;
import java.util.*;
import com.github.braisdom.jds.ast.*;

/** Token Manager. */
@SuppressWarnings ("unused")
class ParserTokenManager implements ParserConstants {

  /** Debug output. */
  public  java.io.PrintStream debugStream = System.out;
  /** Set debug output. */
  public  void setDebugStream(java.io.PrintStream ds) { debugStream = ds; }
private final int jjStopStringLiteralDfa_0(int pos, long active0){
   switch (pos)
   {
      case 0:
         if ((active0 & 0x800000000L) != 0L)
            return 49;
         if ((active0 & 0x1000000000L) != 0L)
            return 50;
         if ((active0 & 0x35a0000000000L) != 0L)
         {
            jjmatchedKind = 56;
            return 16;
         }
         if ((active0 & 0x1000000000000000L) != 0L)
            return 20;
         if ((active0 & 0x40000000000L) != 0L)
         {
            jjmatchedKind = 56;
            return 24;
         }
         if ((active0 & 0x800000L) != 0L)
            return 31;
         if ((active0 & 0x7c000000000000L) != 0L)
         {
            jjmatchedKind = 55;
            return 51;
         }
         if ((active0 & 0x800000200000L) != 0L)
            return 0;
         if ((active0 & 0x200000000000L) != 0L)
         {
            jjmatchedKind = 56;
            return 28;
         }
         return -1;
      case 1:
         if ((active0 & 0x37e0000000000L) != 0L)
         {
            jjmatchedKind = 56;
            jjmatchedPos = 1;
            return 16;
         }
         if ((active0 & 0x7c000000000000L) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 1;
            return 52;
         }
         return -1;
      case 2:
         if ((active0 & 0x37e0000000000L) != 0L)
         {
            jjmatchedKind = 56;
            jjmatchedPos = 2;
            return 16;
         }
         if ((active0 & 0x7c000000000000L) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 2;
            return 52;
         }
         return -1;
      case 3:
         if ((active0 & 0x2200000000000L) != 0L)
            return 16;
         if ((active0 & 0x7c000000000000L) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 3;
            return 52;
         }
         if ((active0 & 0x15e0000000000L) != 0L)
         {
            jjmatchedKind = 56;
            jjmatchedPos = 3;
            return 16;
         }
         return -1;
      case 4:
         if ((active0 & 0x6c000000000000L) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 4;
            return 52;
         }
         if ((active0 & 0x10000000000000L) != 0L)
            return 52;
         if ((active0 & 0x15e0000000000L) != 0L)
         {
            jjmatchedKind = 56;
            jjmatchedPos = 4;
            return 16;
         }
         return -1;
      case 5:
         if ((active0 & 0x5c0000000000L) != 0L)
         {
            jjmatchedKind = 56;
            jjmatchedPos = 5;
            return 16;
         }
         if ((active0 & 0x1020000000000L) != 0L)
            return 16;
         if ((active0 & 0x2c000000000000L) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 5;
            return 52;
         }
         if ((active0 & 0x40000000000000L) != 0L)
            return 52;
         return -1;
      case 6:
         if ((active0 & 0xc0000000000L) != 0L)
            return 16;
         if ((active0 & 0x500000000000L) != 0L)
         {
            jjmatchedKind = 56;
            jjmatchedPos = 6;
            return 16;
         }
         if ((active0 & 0x28000000000000L) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 6;
            return 52;
         }
         if ((active0 & 0x4000000000000L) != 0L)
            return 52;
         return -1;
      case 7:
         if ((active0 & 0x28000000000000L) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 7;
            return 52;
         }
         if ((active0 & 0x500000000000L) != 0L)
         {
            jjmatchedKind = 56;
            jjmatchedPos = 7;
            return 16;
         }
         return -1;
      case 8:
         if ((active0 & 0x100000000000L) != 0L)
         {
            jjmatchedKind = 56;
            jjmatchedPos = 8;
            return 16;
         }
         if ((active0 & 0x400000000000L) != 0L)
            return 16;
         if ((active0 & 0x28000000000000L) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 8;
            return 52;
         }
         return -1;
      case 9:
         if ((active0 & 0x100000000000L) != 0L)
            return 16;
         if ((active0 & 0x8000000000000L) != 0L)
         {
            jjmatchedKind = 55;
            jjmatchedPos = 9;
            return 52;
         }
         if ((active0 & 0x20000000000000L) != 0L)
            return 52;
         return -1;
      default :
         return -1;
   }
}
private final int jjStartNfa_0(int pos, long active0){
   return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
}
private int jjStopAtPos(int pos, int kind)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   return pos + 1;
}
private int jjMoveStringLiteralDfa0_0(){
   switch(curChar)
   {
      case 33:
         return jjMoveStringLiteralDfa1_0(0x4000L);
      case 34:
         return jjStartNfaWithStates_0(0, 36, 50);
      case 35:
         return jjStopAtPos(0, 61);
      case 37:
         return jjStopAtPos(0, 24);
      case 38:
         return jjMoveStringLiteralDfa1_0(0x30000L);
      case 39:
         return jjStartNfaWithStates_0(0, 35, 49);
      case 40:
         return jjStopAtPos(0, 25);
      case 41:
         return jjStopAtPos(0, 26);
      case 42:
         return jjStopAtPos(0, 22);
      case 43:
         return jjStopAtPos(0, 20);
      case 44:
         return jjStopAtPos(0, 32);
      case 45:
         jjmatchedKind = 21;
         return jjMoveStringLiteralDfa1_0(0x800000000000L);
      case 46:
         return jjStopAtPos(0, 33);
      case 47:
         return jjStartNfaWithStates_0(0, 23, 31);
      case 48:
         return jjStartNfaWithStates_0(0, 60, 20);
      case 58:
         return jjStopAtPos(0, 34);
      case 59:
         return jjStopAtPos(0, 31);
      case 60:
         jjmatchedKind = 11;
         return jjMoveStringLiteralDfa1_0(0x1000L);
      case 61:
         return jjMoveStringLiteralDfa1_0(0x200L);
      case 62:
         jjmatchedKind = 10;
         return jjMoveStringLiteralDfa1_0(0x2000L);
      case 74:
         return jjMoveStringLiteralDfa1_0(0x7c000000000000L);
      case 91:
         return jjStopAtPos(0, 29);
      case 93:
         return jjStopAtPos(0, 30);
      case 100:
         return jjMoveStringLiteralDfa1_0(0x80000000000L);
      case 102:
         return jjMoveStringLiteralDfa1_0(0x200000000000L);
      case 105:
         return jjMoveStringLiteralDfa1_0(0x20000000000L);
      case 110:
         return jjMoveStringLiteralDfa1_0(0x2000000000000L);
      case 112:
         return jjMoveStringLiteralDfa1_0(0x500000000000L);
      case 114:
         return jjMoveStringLiteralDfa1_0(0x1000000000000L);
      case 116:
         return jjMoveStringLiteralDfa1_0(0x40000000000L);
      case 123:
         return jjStopAtPos(0, 27);
      case 124:
         return jjMoveStringLiteralDfa1_0(0x8000L);
      case 125:
         return jjStopAtPos(0, 28);
      case 126:
         jjmatchedKind = 19;
         return jjMoveStringLiteralDfa1_0(0x40000L);
      default :
         return jjMoveNfa_0(5, 0);
   }
}
private int jjMoveStringLiteralDfa1_0(long active0){
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(0, active0);
      return 1;
   }
   switch(curChar)
   {
      case 38:
         if ((active0 & 0x10000L) != 0L)
            return jjStopAtPos(1, 16);
         break;
      case 61:
         if ((active0 & 0x200L) != 0L)
            return jjStopAtPos(1, 9);
         else if ((active0 & 0x1000L) != 0L)
            return jjStopAtPos(1, 12);
         else if ((active0 & 0x2000L) != 0L)
            return jjStopAtPos(1, 13);
         else if ((active0 & 0x4000L) != 0L)
            return jjStopAtPos(1, 14);
         else if ((active0 & 0x20000L) != 0L)
            return jjStopAtPos(1, 17);
         else if ((active0 & 0x40000L) != 0L)
            return jjStopAtPos(1, 18);
         break;
      case 62:
         if ((active0 & 0x800000000000L) != 0L)
            return jjStopAtPos(1, 47);
         break;
      case 80:
         return jjMoveStringLiteralDfa2_0(active0, 0x28000000000000L);
      case 81:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000000000L);
      case 83:
         return jjMoveStringLiteralDfa2_0(active0, 0x4000000000000L);
      case 84:
         return jjMoveStringLiteralDfa2_0(active0, 0x10000000000000L);
      case 97:
         return jjMoveStringLiteralDfa2_0(active0, 0x80000000000L);
      case 101:
         return jjMoveStringLiteralDfa2_0(active0, 0x1000000000000L);
      case 109:
         return jjMoveStringLiteralDfa2_0(active0, 0x20000000000L);
      case 114:
         return jjMoveStringLiteralDfa2_0(active0, 0x700000000000L);
      case 117:
         return jjMoveStringLiteralDfa2_0(active0, 0x2000000000000L);
      case 121:
         return jjMoveStringLiteralDfa2_0(active0, 0x40000000000L);
      case 124:
         if ((active0 & 0x8000L) != 0L)
            return jjStopAtPos(1, 15);
         break;
      default :
         break;
   }
   return jjStartNfa_0(0, active0);
}
private int jjMoveStringLiteralDfa2_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(0, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(1, active0);
      return 2;
   }
   switch(curChar)
   {
      case 101:
         return jjMoveStringLiteralDfa3_0(active0, 0x400000000000L);
      case 108:
         return jjMoveStringLiteralDfa3_0(active0, 0x2000000000000L);
      case 111:
         return jjMoveStringLiteralDfa3_0(active0, 0x300000000000L);
      case 112:
         return jjMoveStringLiteralDfa3_0(active0, 0x60000000000L);
      case 114:
         return jjMoveStringLiteralDfa3_0(active0, 0x28000000000000L);
      case 116:
         return jjMoveStringLiteralDfa3_0(active0, 0x1080000000000L);
      case 117:
         return jjMoveStringLiteralDfa3_0(active0, 0x40000000000000L);
      case 121:
         return jjMoveStringLiteralDfa3_0(active0, 0x14000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(1, active0);
}
private int jjMoveStringLiteralDfa3_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(1, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(2, active0);
      return 3;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa4_0(active0, 0x80000000000L);
      case 100:
         return jjMoveStringLiteralDfa4_0(active0, 0x400000000000L);
      case 101:
         return jjMoveStringLiteralDfa4_0(active0, 0x60040000000000L);
      case 106:
         return jjMoveStringLiteralDfa4_0(active0, 0x100000000000L);
      case 108:
         if ((active0 & 0x2000000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 49, 16);
         break;
      case 109:
         if ((active0 & 0x200000000000L) != 0L)
            return jjStartNfaWithStates_0(3, 45, 16);
         return jjMoveStringLiteralDfa4_0(active0, 0x4000000000000L);
      case 111:
         return jjMoveStringLiteralDfa4_0(active0, 0x8020000000000L);
      case 112:
         return jjMoveStringLiteralDfa4_0(active0, 0x10000000000000L);
      case 117:
         return jjMoveStringLiteralDfa4_0(active0, 0x1000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(2, active0);
}
private int jjMoveStringLiteralDfa4_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(2, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(3, active0);
      return 4;
   }
   switch(curChar)
   {
      case 98:
         return jjMoveStringLiteralDfa5_0(active0, 0x4000000000000L);
      case 100:
         return jjMoveStringLiteralDfa5_0(active0, 0x20040000000000L);
      case 101:
         if ((active0 & 0x10000000000000L) != 0L)
            return jjStartNfaWithStates_0(4, 52, 52);
         return jjMoveStringLiteralDfa5_0(active0, 0x100000000000L);
      case 105:
         return jjMoveStringLiteralDfa5_0(active0, 0x400000000000L);
      case 106:
         return jjMoveStringLiteralDfa5_0(active0, 0x8000000000000L);
      case 114:
         return jjMoveStringLiteralDfa5_0(active0, 0x41020000000000L);
      case 115:
         return jjMoveStringLiteralDfa5_0(active0, 0x80000000000L);
      default :
         break;
   }
   return jjStartNfa_0(3, active0);
}
private int jjMoveStringLiteralDfa5_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(3, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(4, active0);
      return 5;
   }
   switch(curChar)
   {
      case 99:
         return jjMoveStringLiteralDfa6_0(active0, 0x500000000000L);
      case 101:
         return jjMoveStringLiteralDfa6_0(active0, 0x80c0000000000L);
      case 105:
         return jjMoveStringLiteralDfa6_0(active0, 0x20000000000000L);
      case 110:
         if ((active0 & 0x1000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 48, 16);
         break;
      case 111:
         return jjMoveStringLiteralDfa6_0(active0, 0x4000000000000L);
      case 116:
         if ((active0 & 0x20000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 41, 16);
         break;
      case 121:
         if ((active0 & 0x40000000000000L) != 0L)
            return jjStartNfaWithStates_0(5, 54, 52);
         break;
      default :
         break;
   }
   return jjStartNfa_0(4, active0);
}
private int jjMoveStringLiteralDfa6_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(4, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(5, active0);
      return 6;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa7_0(active0, 0x400000000000L);
      case 99:
         return jjMoveStringLiteralDfa7_0(active0, 0x28000000000000L);
      case 102:
         if ((active0 & 0x40000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 42, 16);
         break;
      case 108:
         if ((active0 & 0x4000000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 50, 52);
         break;
      case 116:
         if ((active0 & 0x80000000000L) != 0L)
            return jjStartNfaWithStates_0(6, 43, 16);
         return jjMoveStringLiteralDfa7_0(active0, 0x100000000000L);
      default :
         break;
   }
   return jjStartNfa_0(5, active0);
}
private int jjMoveStringLiteralDfa7_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(5, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(6, active0);
      return 7;
   }
   switch(curChar)
   {
      case 97:
         return jjMoveStringLiteralDfa8_0(active0, 0x20000000000000L);
      case 105:
         return jjMoveStringLiteralDfa8_0(active0, 0x100000000000L);
      case 116:
         return jjMoveStringLiteralDfa8_0(active0, 0x8400000000000L);
      default :
         break;
   }
   return jjStartNfa_0(6, active0);
}
private int jjMoveStringLiteralDfa8_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(6, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(7, active0);
      return 8;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x400000000000L) != 0L)
            return jjStartNfaWithStates_0(8, 46, 16);
         break;
      case 105:
         return jjMoveStringLiteralDfa9_0(active0, 0x8000000000000L);
      case 111:
         return jjMoveStringLiteralDfa9_0(active0, 0x100000000000L);
      case 116:
         return jjMoveStringLiteralDfa9_0(active0, 0x20000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(7, active0);
}
private int jjMoveStringLiteralDfa9_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(7, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(8, active0);
      return 9;
   }
   switch(curChar)
   {
      case 101:
         if ((active0 & 0x20000000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 53, 52);
         break;
      case 110:
         if ((active0 & 0x100000000000L) != 0L)
            return jjStartNfaWithStates_0(9, 44, 16);
         break;
      case 111:
         return jjMoveStringLiteralDfa10_0(active0, 0x8000000000000L);
      default :
         break;
   }
   return jjStartNfa_0(8, active0);
}
private int jjMoveStringLiteralDfa10_0(long old0, long active0){
   if (((active0 &= old0)) == 0L)
      return jjStartNfa_0(8, old0);
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) {
      jjStopStringLiteralDfa_0(9, active0);
      return 10;
   }
   switch(curChar)
   {
      case 110:
         if ((active0 & 0x8000000000000L) != 0L)
            return jjStartNfaWithStates_0(10, 51, 52);
         break;
      default :
         break;
   }
   return jjStartNfa_0(9, active0);
}
private int jjStartNfaWithStates_0(int pos, int kind, int state)
{
   jjmatchedKind = kind;
   jjmatchedPos = pos;
   try { curChar = input_stream.readChar(); }
   catch(java.io.IOException e) { return pos + 1; }
   return jjMoveNfa_0(state, pos + 1);
}
static final long[] jjbitVec0 = {
   0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL
};
static final long[] jjbitVec2 = {
   0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
};
private int jjMoveNfa_0(int startState, int curPos)
{
   int startsAt = 0;
   jjnewStateCnt = 49;
   int i = 1;
   jjstateSet[0] = startState;
   int kind = 0x7fffffff;
   for (;;)
   {
      if (++jjround == 0x7fffffff)
         ReInitRounds();
      if (curChar < 64)
      {
         long l = 1L << curChar;
         do
         {
            switch(jjstateSet[--i])
            {
               case 20:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(19, 20); }
                  else if (curChar == 46)
                  {
                     if (kind > 62)
                        kind = 62;
                     { jjCheckNAdd(21); }
                  }
                  break;
               case 28:
               case 16:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  { jjCheckNAdd(16); }
                  break;
               case 5:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(19, 20); }
                  else if (curChar == 45)
                     { jjCheckNAddTwoStates(17, 19); }
                  else if (curChar == 39)
                     { jjCheckNAddStates(0, 3); }
                  else if (curChar == 47)
                     { jjAddStates(4, 5); }
                  else if (curChar == 34)
                     { jjCheckNAddTwoStates(7, 8); }
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 59)
                        kind = 59;
                     { jjCheckNAdd(18); }
                  }
                  else if (curChar == 45)
                     jjstateSet[jjnewStateCnt++] = 0;
                  break;
               case 31:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(37, 38); }
                  else if (curChar == 47)
                     { jjCheckNAddStates(6, 8); }
                  break;
               case 0:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(19, 20); }
                  else if (curChar == 45)
                     { jjCheckNAddStates(9, 11); }
                  if ((0x3fe000000000000L & l) != 0L)
                  {
                     if (kind > 59)
                        kind = 59;
                     { jjCheckNAdd(18); }
                  }
                  break;
               case 49:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     { jjCheckNAddTwoStates(43, 44); }
                  else if (curChar == 39)
                  {
                     if (kind > 40)
                        kind = 40;
                  }
                  if (curChar == 39)
                  {
                     if (kind > 37)
                        kind = 37;
                  }
                  break;
               case 24:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  { jjCheckNAdd(16); }
                  break;
               case 50:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     { jjCheckNAddTwoStates(7, 8); }
                  else if (curChar == 34)
                  {
                     if (kind > 38)
                        kind = 38;
                  }
                  break;
               case 51:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  { jjCheckNAdd(16); }
                  break;
               case 52:
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 56)
                        kind = 56;
                     { jjCheckNAdd(16); }
                  }
                  if ((0x3ff000000000000L & l) != 0L)
                  {
                     if (kind > 55)
                        kind = 55;
                     { jjCheckNAddTwoStates(13, 14); }
                  }
                  break;
               case 1:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     { jjCheckNAddStates(9, 11); }
                  break;
               case 2:
                  if ((0x2400L & l) != 0L && kind > 8)
                     kind = 8;
                  break;
               case 3:
                  if (curChar == 10 && kind > 8)
                     kind = 8;
                  break;
               case 4:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 3;
                  break;
               case 6:
                  if (curChar == 34)
                     { jjCheckNAddTwoStates(7, 8); }
                  break;
               case 7:
                  if ((0xfffffffbffffdbffL & l) != 0L)
                     { jjCheckNAddTwoStates(7, 8); }
                  break;
               case 8:
                  if (curChar == 34 && kind > 38)
                     kind = 38;
                  break;
               case 10:
                  { jjAddStates(12, 13); }
                  break;
               case 14:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  { jjCheckNAddTwoStates(13, 14); }
                  break;
               case 17:
                  if ((0x3fe000000000000L & l) == 0L)
                     break;
                  if (kind > 59)
                     kind = 59;
                  { jjCheckNAdd(18); }
                  break;
               case 18:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 59)
                     kind = 59;
                  { jjCheckNAdd(18); }
                  break;
               case 19:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddTwoStates(19, 20); }
                  break;
               case 21:
                  if ((0x3ff000000000000L & l) == 0L)
                     break;
                  if (kind > 62)
                     kind = 62;
                  { jjCheckNAdd(21); }
                  break;
               case 30:
                  if (curChar == 47)
                     { jjAddStates(4, 5); }
                  break;
               case 32:
                  if ((0xffffffffffffdbffL & l) != 0L)
                     { jjCheckNAddStates(6, 8); }
                  break;
               case 33:
                  if ((0x2400L & l) != 0L && kind > 6)
                     kind = 6;
                  break;
               case 34:
                  if (curChar == 10 && kind > 6)
                     kind = 6;
                  break;
               case 35:
                  if (curChar == 13)
                     jjstateSet[jjnewStateCnt++] = 34;
                  break;
               case 36:
                  if (curChar == 42)
                     { jjCheckNAddTwoStates(37, 38); }
                  break;
               case 37:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(37, 38); }
                  break;
               case 38:
                  if (curChar == 42)
                     { jjAddStates(14, 15); }
                  break;
               case 39:
                  if ((0xffff7fffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(40, 38); }
                  break;
               case 40:
                  if ((0xfffffbffffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(40, 38); }
                  break;
               case 41:
                  if (curChar == 47 && kind > 7)
                     kind = 7;
                  break;
               case 42:
                  if (curChar == 39)
                     { jjCheckNAddStates(0, 3); }
                  break;
               case 43:
                  if ((0xffffff7fffffdbffL & l) != 0L)
                     { jjCheckNAddTwoStates(43, 44); }
                  break;
               case 44:
                  if (curChar == 39 && kind > 37)
                     kind = 37;
                  break;
               case 46:
                  if ((0x3ff000000000000L & l) != 0L)
                     { jjCheckNAddStates(16, 18); }
                  break;
               case 47:
                  if (curChar == 39 && kind > 40)
                     kind = 40;
                  break;
               case 48:
                  if (curChar == 45)
                     { jjCheckNAddTwoStates(17, 19); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else if (curChar < 128)
      {
         long l = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 28:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 56)
                        kind = 56;
                     { jjCheckNAdd(16); }
                  }
                  if (curChar == 97)
                     jjstateSet[jjnewStateCnt++] = 27;
                  break;
               case 5:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 56)
                        kind = 56;
                     { jjCheckNAdd(16); }
                  }
                  else if (curChar == 96)
                     { jjCheckNAdd(10); }
                  if ((0x7fffffeL & l) != 0L)
                  {
                     if (kind > 55)
                        kind = 55;
                     { jjCheckNAdd(13); }
                  }
                  else if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 28;
                  else if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 49:
                  { jjCheckNAddTwoStates(43, 44); }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddStates(16, 18); }
                  break;
               case 24:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 56)
                        kind = 56;
                     { jjCheckNAdd(16); }
                  }
                  if (curChar == 114)
                     jjstateSet[jjnewStateCnt++] = 23;
                  break;
               case 50:
               case 7:
                  { jjCheckNAddTwoStates(7, 8); }
                  break;
               case 51:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 56)
                        kind = 56;
                     { jjCheckNAdd(16); }
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 55)
                        kind = 55;
                     { jjCheckNAddTwoStates(13, 14); }
                  }
                  break;
               case 52:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 56)
                        kind = 56;
                     { jjCheckNAdd(16); }
                  }
                  if ((0x7fffffe87fffffeL & l) != 0L)
                  {
                     if (kind > 55)
                        kind = 55;
                     { jjCheckNAddTwoStates(13, 14); }
                  }
                  if ((0x7fffffe07fffffeL & l) != 0L)
                  {
                     if (kind > 55)
                        kind = 55;
                     { jjCheckNAddTwoStates(13, 14); }
                  }
                  break;
               case 1:
                  { jjAddStates(9, 11); }
                  break;
               case 9:
                  if (curChar == 96)
                     { jjCheckNAdd(10); }
                  break;
               case 10:
                  if ((0xfffffffeffffffffL & l) != 0L)
                     { jjCheckNAddTwoStates(10, 11); }
                  break;
               case 11:
                  if (curChar == 96 && kind > 39)
                     kind = 39;
                  break;
               case 12:
                  if ((0x7fffffeL & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  { jjCheckNAdd(13); }
                  break;
               case 13:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  { jjCheckNAddTwoStates(13, 14); }
                  break;
               case 14:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 55)
                     kind = 55;
                  { jjCheckNAddTwoStates(13, 14); }
                  break;
               case 15:
                  if ((0x7fffffe07fffffeL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  { jjCheckNAdd(16); }
                  break;
               case 16:
                  if ((0x7fffffe87fffffeL & l) == 0L)
                     break;
                  if (kind > 56)
                     kind = 56;
                  { jjCheckNAdd(16); }
                  break;
               case 22:
                  if (curChar == 101 && kind > 63)
                     kind = 63;
                  break;
               case 23:
                  if (curChar == 117)
                     { jjCheckNAdd(22); }
                  break;
               case 25:
                  if (curChar == 116)
                     jjstateSet[jjnewStateCnt++] = 24;
                  break;
               case 26:
                  if (curChar == 115)
                     { jjCheckNAdd(22); }
                  break;
               case 27:
                  if (curChar == 108)
                     jjstateSet[jjnewStateCnt++] = 26;
                  break;
               case 29:
                  if (curChar == 102)
                     jjstateSet[jjnewStateCnt++] = 28;
                  break;
               case 32:
                  { jjAddStates(6, 8); }
                  break;
               case 37:
                  { jjCheckNAddTwoStates(37, 38); }
                  break;
               case 39:
               case 40:
                  { jjCheckNAddTwoStates(40, 38); }
                  break;
               case 43:
                  { jjCheckNAddTwoStates(43, 44); }
                  break;
               case 45:
                  if ((0x7fffffe07fffffeL & l) != 0L)
                     { jjCheckNAddStates(16, 18); }
                  break;
               case 46:
                  if ((0x7fffffe87fffffeL & l) != 0L)
                     { jjCheckNAddStates(16, 18); }
                  break;
               default : break;
            }
         } while(i != startsAt);
      }
      else
      {
         int hiByte = (curChar >> 8);
         int i1 = hiByte >> 6;
         long l1 = 1L << (hiByte & 077);
         int i2 = (curChar & 0xff) >> 6;
         long l2 = 1L << (curChar & 077);
         do
         {
            switch(jjstateSet[--i])
            {
               case 49:
               case 43:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddTwoStates(43, 44); }
                  break;
               case 50:
               case 7:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddTwoStates(7, 8); }
                  break;
               case 1:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjAddStates(9, 11); }
                  break;
               case 10:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjAddStates(12, 13); }
                  break;
               case 32:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjAddStates(6, 8); }
                  break;
               case 37:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddTwoStates(37, 38); }
                  break;
               case 39:
               case 40:
                  if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                     { jjCheckNAddTwoStates(40, 38); }
                  break;
               default : if (i1 == 0 || l1 == 0 || i2 == 0 ||  l2 == 0) break; else break;
            }
         } while(i != startsAt);
      }
      if (kind != 0x7fffffff)
      {
         jjmatchedKind = kind;
         jjmatchedPos = curPos;
         kind = 0x7fffffff;
      }
      ++curPos;
      if ((i = jjnewStateCnt) == (startsAt = 49 - (jjnewStateCnt = startsAt)))
         return curPos;
      try { curChar = input_stream.readChar(); }
      catch(java.io.IOException e) { return curPos; }
   }
}

/** Token literal values. */
public static final String[] jjstrLiteralImages = {
"", null, null, null, null, null, null, null, null, "\75\75", "\76", "\74", 
"\74\75", "\76\75", "\41\75", "\174\174", "\46\46", "\46\75", "\176\75", "\176", "\53", 
"\55", "\52", "\57", "\45", "\50", "\51", "\173", "\175", "\133", "\135", "\73", 
"\54", "\56", "\72", "\47", "\42", null, null, null, null, 
"\151\155\160\157\162\164", "\164\171\160\145\144\145\146", "\144\141\164\141\163\145\164", 
"\160\162\157\152\145\143\164\151\157\156", "\146\162\157\155", "\160\162\145\144\151\143\141\164\145", "\55\76", 
"\162\145\164\165\162\156", "\156\165\154\154", "\112\123\171\155\142\157\154", 
"\112\120\162\157\152\145\143\164\151\157\156", "\112\124\171\160\145", "\112\120\162\145\144\151\143\141\164\145", 
"\112\121\165\145\162\171", null, null, null, null, null, "\60", "\43", null, null, };
protected Token jjFillToken()
{
   final Token t;
   final String curTokenImage;
   String im = jjstrLiteralImages[jjmatchedKind];
   curTokenImage = (im == null) ? input_stream.GetImage() : im;
   t = Token.newToken(jjmatchedKind, curTokenImage);

   return t;
}
static final int[] jjnextStates = {
   43, 44, 45, 47, 31, 36, 32, 33, 35, 1, 2, 4, 10, 11, 39, 41, 
   45, 46, 47, 
};
private static final boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2)
{
   switch(hiByte)
   {
      case 0:
         return ((jjbitVec2[i2] & l2) != 0L);
      default :
         if ((jjbitVec0[i1] & l1) != 0L)
            return true;
         return false;
   }
}

int curLexState = 0;
int defaultLexState = 0;
int jjnewStateCnt;
int jjround;
int jjmatchedPos;
int jjmatchedKind;

/** Get the next Token. */
public Token getNextToken() 
{
  Token matchedToken;
  int curPos = 0;

  EOFLoop :
  for (;;)
  {
   try
   {
      curChar = input_stream.BeginToken();
   }
   catch(Exception e)
   {
      jjmatchedKind = 0;
      jjmatchedPos = -1;
      matchedToken = jjFillToken();
      return matchedToken;
   }

   try { input_stream.backup(0);
      while (curChar <= 32 && (0x100003600L & (1L << curChar)) != 0L)
         curChar = input_stream.BeginToken();
   }
   catch (java.io.IOException e1) { continue EOFLoop; }
   jjmatchedKind = 0x7fffffff;
   jjmatchedPos = 0;
   curPos = jjMoveStringLiteralDfa0_0();
   if (jjmatchedKind != 0x7fffffff)
   {
      if (jjmatchedPos + 1 < curPos)
         input_stream.backup(curPos - jjmatchedPos - 1);
      if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L)
      {
         matchedToken = jjFillToken();
         return matchedToken;
      }
      else
      {
         continue EOFLoop;
      }
   }
   int error_line = input_stream.getEndLine();
   int error_column = input_stream.getEndColumn();
   String error_after = null;
   boolean EOFSeen = false;
   try { input_stream.readChar(); input_stream.backup(1); }
   catch (java.io.IOException e1) {
      EOFSeen = true;
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
      if (curChar == '\n' || curChar == '\r') {
         error_line++;
         error_column = 0;
      }
      else
         error_column++;
   }
   if (!EOFSeen) {
      input_stream.backup(1);
      error_after = curPos <= 1 ? "" : input_stream.GetImage();
   }
   throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
  }
}

void SkipLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void MoreLexicalActions()
{
   jjimageLen += (lengthOfMatch = jjmatchedPos + 1);
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
void TokenLexicalActions(Token matchedToken)
{
   switch(jjmatchedKind)
   {
      default :
         break;
   }
}
private void jjCheckNAdd(int state)
{
   if (jjrounds[state] != jjround)
   {
      jjstateSet[jjnewStateCnt++] = state;
      jjrounds[state] = jjround;
   }
}
private void jjAddStates(int start, int end)
{
   do {
      jjstateSet[jjnewStateCnt++] = jjnextStates[start];
   } while (start++ != end);
}
private void jjCheckNAddTwoStates(int state1, int state2)
{
   jjCheckNAdd(state1);
   jjCheckNAdd(state2);
}

private void jjCheckNAddStates(int start, int end)
{
   do {
      jjCheckNAdd(jjnextStates[start]);
   } while (start++ != end);
}

    /** Constructor. */
    public ParserTokenManager(SimpleCharStream stream){

      if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");

    input_stream = stream;
  }

  /** Constructor. */
  public ParserTokenManager (SimpleCharStream stream, int lexState){
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Reinitialise parser. */
  
  public void ReInit(SimpleCharStream stream)
  {


    jjmatchedPos =
    jjnewStateCnt =
    0;
    curLexState = defaultLexState;
    input_stream = stream;
    ReInitRounds();
  }

  private void ReInitRounds()
  {
    int i;
    jjround = 0x80000001;
    for (i = 49; i-- > 0;)
      jjrounds[i] = 0x80000000;
  }

  /** Reinitialise parser. */
  public void ReInit(SimpleCharStream stream, int lexState)
  
  {
    ReInit(stream);
    SwitchTo(lexState);
  }

  /** Switch to specified lex state. */
  public void SwitchTo(int lexState)
  {
    if (lexState >= 1 || lexState < 0)
      throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
    else
      curLexState = lexState;
  }


/** Lexer state names. */
public static final String[] lexStateNames = {
   "DEFAULT",
};

/** Lex State array. */
public static final int[] jjnewLexState = {
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
   -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
};
static final long[] jjtoToken = {
   0xf9fffffffffffe01L, 0x0L, 
};
static final long[] jjtoSkip = {
   0x1feL, 0x0L, 
};
static final long[] jjtoSpecial = {
   0x0L, 0x0L, 
};
static final long[] jjtoMore = {
   0x0L, 0x0L, 
};
    protected SimpleCharStream  input_stream;

    private final int[] jjrounds = new int[49];
    private final int[] jjstateSet = new int[2 * 49];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected int curChar;
}
