/* Parser.java */
/* Generated By:JavaCC: Do not edit this line. Parser.java */
package com.github.braisdom.jds;

import java.util.*;
import com.github.braisdom.jds.ast.*;

public final class Parser implements ParserConstants {

    public static String unquote(String value, String quote) {
        if (value.startsWith(quote) && (value.endsWith(quote))) {
            return value.substring(1, value.length() - 1);
        }
        return value;
    }

  final public SqlNode SqlNode() throws ParseException {final SqlNode sqlNode = new SqlNode();
    ImportNode importNode;
    DatasetNode datasetNode;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IMPORT:
      case TYPEDEF:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IMPORT:{
        importNode = ImportNode();
sqlNode.addImportNode(importNode);
        break;
        }
      case TYPEDEF:{
        datasetNode = DatasetNode();
sqlNode.addDatasetNode(datasetNode);
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return sqlNode;}
    throw new Error("Missing return statement in function");
}

  final public ImportNode ImportNode() throws ParseException {ImportNode importNode;
    String importDeclaration;
    jj_consume_token(IMPORT);
    importDeclaration = Name();
importNode = new ImportNode(importDeclaration);
    jj_consume_token(SEMICOLON);
{if ("" != null) return importNode;}
    throw new Error("Missing return statement in function");
}

  final public DatasetNode DatasetNode() throws ParseException {final DatasetNode datasetNode = new DatasetNode();
    FromNode fromNode;
    ExpressionNode logicExpressionNode;
    jj_consume_token(TYPEDEF);
    jj_consume_token(DATASET);
    jj_consume_token(TYPE_NAME);
datasetNode.setName(token.image);
    jj_consume_token(LPAREN);
    DatasetParameter(datasetNode);
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACE);
    jj_consume_token(PROJECTION);
    ProjectionList(datasetNode);
    jj_consume_token(COMMA);
    jj_consume_token(FROM);
    FromNode(datasetNode);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COMMA:{
      jj_consume_token(COMMA);
      jj_consume_token(PREDICATE);
      jj_consume_token(LPAREN);
      logicExpressionNode = CompareExpressionNode();
      jj_consume_token(RPAREN);
datasetNode.setPredicate(logicExpressionNode);
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
    jj_consume_token(RBRACE);
{if ("" != null) return datasetNode;}
    throw new Error("Missing return statement in function");
}

  final public void DatasetParameter(DatasetNode datasetNode) throws ParseException {FormalParameterNode parameter;
    parameter = FormalParameterNode();
datasetNode.addFormalParameter(parameter);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        ;
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        break label_2;
      }
      jj_consume_token(COMMA);
      parameter = FormalParameterNode();
datasetNode.addFormalParameter(parameter);
    }
}

  final public void ProjectionList(DatasetNode datasetNode) throws ParseException {Projectional projectional;
    jj_consume_token(LBRACKET);
    projectional = Projectional();
datasetNode.addProjectional(projectional);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_3;
      }
      jj_consume_token(COMMA);
      projectional = Projectional();
datasetNode.addProjectional(projectional);
    }
    jj_consume_token(RBRACKET);
}

  final public Projectional Projectional() throws ParseException {Projectional projectional = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STRINGVAL:
    case NULL:
    case DECIMAL_LITERAL:
    case ZERO:
    case FLOATING_LITERAL:{
      projectional = SqlLiteral();
      jj_consume_token(AS);
      jj_consume_token(STRINGVAL);
projectional.setAlias(token.image);
      break;
      }
    case COLON:
    case NUMBER_SIGN:{
      projectional = SymbolNode();
      jj_consume_token(AS);
      jj_consume_token(STRINGVAL);
projectional.setAlias(token.image);
      break;
      }
    case TYPE_NAME:
    case IDENTIFIER:{
      projectional = SqlFunctionCallNode();
      jj_consume_token(AS);
      jj_consume_token(STRINGVAL);
projectional.setAlias(token.image);
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return projectional;}
    throw new Error("Missing return statement in function");
}

  final public void FromNode(DatasetNode dataset) throws ParseException {FromNode fromNode;
    fromNode = SymbolNode();
dataset.setFromNode(fromNode);
}

  final public FormalParameterNode FormalParameterNode() throws ParseException {String type;
    String name;
    jj_consume_token(TYPE_NAME);
type = getToken(0).image;
    jj_consume_token(IDENTIFIER);
name = getToken(0).image;
{if ("" != null) return new FormalParameterNode(type, name);}
    throw new Error("Missing return statement in function");
}

  final public SqlFunctionCallNode SqlFunctionCallNode() throws ParseException {SqlFunctionCallNode sqlFunctionCallNode = new SqlFunctionCallNode();
    SqlFunctionOperand operand;
    if (jj_2_1(2)) {
      jj_consume_token(TYPE_NAME);
sqlFunctionCallNode.setType(token.image);
      jj_consume_token(DOT);
    } else {
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFIER:{
      jj_consume_token(IDENTIFIER);
      break;
      }
    case TYPE_NAME:{
      jj_consume_token(TYPE_NAME);
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
sqlFunctionCallNode.setName(getToken(0).image);
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COLON:
    case STRINGVAL:
    case NULL:
    case TYPE_NAME:
    case IDENTIFIER:
    case DECIMAL_LITERAL:
    case ZERO:
    case NUMBER_SIGN:
    case FLOATING_LITERAL:{
      operand = SqlFunctionOperand();
sqlFunctionCallNode.addOperands(operand);
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[7] = jj_gen;
          break label_4;
        }
        jj_consume_token(COMMA);
        operand = SqlFunctionOperand();
sqlFunctionCallNode.addOperands(operand);
      }
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
{if ("" != null) return sqlFunctionCallNode;}
    throw new Error("Missing return statement in function");
}

  final public SqlFunctionOperand SqlFunctionOperand() throws ParseException {SqlFunctionOperand operand;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STRINGVAL:
    case NULL:
    case DECIMAL_LITERAL:
    case ZERO:
    case FLOATING_LITERAL:{
      operand = SqlLiteral();
{if ("" != null) return operand;}
      break;
      }
    case COLON:
    case NUMBER_SIGN:{
      operand = SymbolNode();
{if ("" != null) return operand;}
      break;
      }
    case TYPE_NAME:
    case IDENTIFIER:{
      operand = SqlFunctionCallNode();
{if ("" != null) return operand;}
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public ExpressionNode MathematicExpressionNode() throws ParseException {ExpressionNode expressionNode = new ExpressionNode();
    Object operand;
    String operator;
expressionNode.setExpressionType(ExpressionType.MATHEMATIC);
    MathematicExpressionOperand(expressionNode);
    operator = MathematicExpressionOperator();
expressionNode.addOperand(operator);
    MathematicExpressionOperand(expressionNode);
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case PLUS:
      case MINUS:
      case STAR:
      case SLASH:
      case REM:{
        ;
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        break label_5;
      }
      operator = MathematicExpressionOperator();
expressionNode.addOperand(operator);
      MathematicExpressionOperand(expressionNode);
    }
{if ("" != null) return expressionNode;}
    throw new Error("Missing return statement in function");
}

  final public void MathematicExpressionOperand(ExpressionNode expressionNode) throws ParseException {ExpressionNode enclosedExpression;
    ExpressionOperand operand = null;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STRINGVAL:
    case NULL:
    case DECIMAL_LITERAL:
    case ZERO:
    case FLOATING_LITERAL:{
      operand = SqlLiteral();
expressionNode.addOperand(operand);
      break;
      }
    case COLON:
    case NUMBER_SIGN:{
      operand = SymbolNode();
expressionNode.addOperand(operand);
      break;
      }
    case LPAREN:{
      jj_consume_token(LPAREN);
      enclosedExpression = MathematicExpressionNode();
expressionNode.addOperand(new EnclosedExpression(enclosedExpression));
      jj_consume_token(RPAREN);
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public ExpressionNode CompareExpressionNode() throws ParseException {ExpressionNode expressionNode = new ExpressionNode();
    Object operand;
    String operator;
expressionNode.setExpressionType(ExpressionType.COMPARE);
    CompareExpressionOperand(expressionNode);
    operator = CompareExpressionOperator();
expressionNode.addOperand(operator);
    CompareExpressionOperand(expressionNode);
{if ("" != null) return expressionNode;}
    throw new Error("Missing return statement in function");
}

  final public void CompareExpressionOperand(ExpressionNode expressionNode) throws ParseException {ExpressionNode enclosedExpression;
    ExpressionOperand operand = null;
    if (jj_2_2(2)) {
      operand = SqlLiteral();
expressionNode.addOperand(operand);
    } else if (jj_2_3(3)) {
      operand = SymbolNode();
expressionNode.addOperand(operand);
    } else if (jj_2_4(2147483647)) {
      jj_consume_token(LPAREN);
      operand = MathematicExpressionNode();
expressionNode.addOperand(operand);
      jj_consume_token(RPAREN);
    } else if (jj_2_5(2147483647)) {
      jj_consume_token(LPAREN);
      enclosedExpression = CompareExpressionNode();
expressionNode.addOperand(new EnclosedExpression(enclosedExpression));
      jj_consume_token(RPAREN);
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public String MathematicExpressionOperator() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PLUS:{
      jj_consume_token(PLUS);
{if ("" != null) return token.image;}
      break;
      }
    case MINUS:{
      jj_consume_token(MINUS);
{if ("" != null) return token.image;}
      break;
      }
    case STAR:{
      jj_consume_token(STAR);
{if ("" != null) return token.image;}
      break;
      }
    case SLASH:{
      jj_consume_token(SLASH);
{if ("" != null) return token.image;}
      break;
      }
    case REM:{
      jj_consume_token(REM);
{if ("" != null) return token.image;}
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public String LogicOperator() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SC_AND:{
      jj_consume_token(SC_AND);
{if ("" != null) return token.image;}
      break;
      }
    case SC_OR:{
      jj_consume_token(SC_OR);
{if ("" != null) return token.image;}
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public String CompareExpressionOperator() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case EQ:{
      jj_consume_token(EQ);
{if ("" != null) return token.image;}
      break;
      }
    case GT:{
      jj_consume_token(GT);
{if ("" != null) return token.image;}
      break;
      }
    case GE:{
      jj_consume_token(GE);
{if ("" != null) return token.image;}
      break;
      }
    case NE:{
      jj_consume_token(NE);
{if ("" != null) return token.image;}
      break;
      }
    case LT:{
      jj_consume_token(LT);
{if ("" != null) return token.image;}
      break;
      }
    case LE:{
      jj_consume_token(LE);
{if ("" != null) return token.image;}
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public SqlLiteral SqlLiteral() throws ParseException {Object value = null;
    Token token;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STRINGVAL:{
      token = jj_consume_token(STRINGVAL);
value = token.image;
      break;
      }
    case DECIMAL_LITERAL:{
      token = jj_consume_token(DECIMAL_LITERAL);
value = Integer.parseInt(token.image);
      break;
      }
    case FLOATING_LITERAL:{
      token = jj_consume_token(FLOATING_LITERAL);
value = Float.parseFloat(token.image);
      break;
      }
    case ZERO:{
      token = jj_consume_token(ZERO);
value = Integer.parseInt(token.image);
      break;
      }
    case NULL:{
      token = jj_consume_token(NULL);
value = null;
      break;
      }
    default:
      jj_la1[15] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return new SqlLiteral(value);}
    throw new Error("Missing return statement in function");
}

  final public SymbolNode SymbolNode() throws ParseException {SymbolNode symbolNode = new SymbolNode();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COLON:{
      jj_consume_token(COLON);
      jj_consume_token(IDENTIFIER);
symbolNode.setSymbolName(token.image);
      break;
      }
    case NUMBER_SIGN:{
      jj_consume_token(NUMBER_SIGN);
      jj_consume_token(IDENTIFIER);
symbolNode.setDatasetName(token.image);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DOT:{
        jj_consume_token(DOT);
        jj_consume_token(IDENTIFIER);
symbolNode.setSymbolName(token.image);
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        ;
      }
      break;
      }
    default:
      jj_la1[17] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return symbolNode;}
    throw new Error("Missing return statement in function");
}

  final public String Name() throws ParseException {List<String> names = new ArrayList();
    jj_consume_token(IDENTIFIER);
names.add(getToken(0).image);
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DOT:{
        ;
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        break label_6;
      }
      jj_consume_token(DOT);
      jj_consume_token(IDENTIFIER);
names.add(getToken(0).image);
    }
{if ("" != null) return String.join(".", names.toArray(new String[0]));}
    throw new Error("Missing return statement in function");
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_3R_CompareExpressionOperator_370_5_39()
 {
    if (jj_scan_token(LE)) return true;
    return false;
  }

  private boolean jj_3R_CompareExpressionOperator_369_5_38()
 {
    if (jj_scan_token(LT)) return true;
    return false;
  }

  private boolean jj_3R_CompareExpressionOperator_368_5_37()
 {
    if (jj_scan_token(NE)) return true;
    return false;
  }

  private boolean jj_3R_MathematicExpressionNode_273_5_9()
 {
    if (jj_3R_MathematicExpressionOperand_293_5_18()) return true;
    if (jj_3R_MathematicExpressionOperator_344_5_19()) return true;
    if (jj_3R_MathematicExpressionOperand_293_5_18()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_MathematicExpressionNode_280_17_20()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_CompareExpressionOperator_367_5_36()
 {
    if (jj_scan_token(GE)) return true;
    return false;
  }

  private boolean jj_3R_CompareExpressionOperator_366_5_35()
 {
    if (jj_scan_token(GT)) return true;
    return false;
  }

  private boolean jj_3R_CompareExpressionOperator_365_5_22()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_CompareExpressionOperator_365_5_34()) {
    jj_scanpos = xsp;
    if (jj_3R_CompareExpressionOperator_366_5_35()) {
    jj_scanpos = xsp;
    if (jj_3R_CompareExpressionOperator_367_5_36()) {
    jj_scanpos = xsp;
    if (jj_3R_CompareExpressionOperator_368_5_37()) {
    jj_scanpos = xsp;
    if (jj_3R_CompareExpressionOperator_369_5_38()) {
    jj_scanpos = xsp;
    if (jj_3R_CompareExpressionOperator_370_5_39()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_CompareExpressionOperator_365_5_34()
 {
    if (jj_scan_token(EQ)) return true;
    return false;
  }

  private boolean jj_3R_MathematicExpressionOperator_349_9_31()
 {
    if (jj_scan_token(REM)) return true;
    return false;
  }

  private boolean jj_3R_MathematicExpressionOperator_348_9_30()
 {
    if (jj_scan_token(SLASH)) return true;
    return false;
  }

  private boolean jj_3R_MathematicExpressionOperator_347_9_29()
 {
    if (jj_scan_token(STAR)) return true;
    return false;
  }

  private boolean jj_3R_MathematicExpressionOperator_346_9_28()
 {
    if (jj_scan_token(MINUS)) return true;
    return false;
  }

  private boolean jj_3R_MathematicExpressionOperator_345_9_27()
 {
    if (jj_scan_token(PLUS)) return true;
    return false;
  }

  private boolean jj_3_5()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_CompareExpressionNode_309_5_10()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_scan_token(TYPE_NAME)) return true;
    if (jj_scan_token(DOT)) return true;
    return false;
  }

  private boolean jj_3R_MathematicExpressionOperator_344_5_19()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_MathematicExpressionOperator_345_9_27()) {
    jj_scanpos = xsp;
    if (jj_3R_MathematicExpressionOperator_346_9_28()) {
    jj_scanpos = xsp;
    if (jj_3R_MathematicExpressionOperator_347_9_29()) {
    jj_scanpos = xsp;
    if (jj_3R_MathematicExpressionOperator_348_9_30()) {
    jj_scanpos = xsp;
    if (jj_3R_MathematicExpressionOperator_349_9_31()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3_4()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_MathematicExpressionNode_273_5_9()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_CompareExpressionOperand_332_9_33()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_CompareExpressionNode_309_5_10()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_CompareExpressionOperand_328_9_32()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_MathematicExpressionNode_273_5_9()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3_3()
 {
    if (jj_3R_SymbolNode_392_5_8()) return true;
    return false;
  }

  private boolean jj_3_2()
 {
    if (jj_3R_SqlLiteral_379_5_7()) return true;
    return false;
  }

  private boolean jj_3R_CompareExpressionOperand_325_5_21()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_2()) {
    jj_scanpos = xsp;
    if (jj_3_3()) {
    jj_scanpos = xsp;
    if (jj_3R_CompareExpressionOperand_328_9_32()) {
    jj_scanpos = xsp;
    if (jj_3R_CompareExpressionOperand_332_9_33()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_CompareExpressionNode_309_5_10()
 {
    if (jj_3R_CompareExpressionOperand_325_5_21()) return true;
    if (jj_3R_CompareExpressionOperator_365_5_22()) return true;
    if (jj_3R_CompareExpressionOperand_325_5_21()) return true;
    return false;
  }

  private boolean jj_3R_SymbolNode_394_9_17()
 {
    if (jj_scan_token(NUMBER_SIGN)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_SymbolNode_394_84_23()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_SymbolNode_393_9_16()
 {
    if (jj_scan_token(COLON)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_MathematicExpressionOperand_296_9_26()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_MathematicExpressionNode_273_5_9()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_MathematicExpressionOperand_295_9_25()
 {
    if (jj_3R_SymbolNode_392_5_8()) return true;
    return false;
  }

  private boolean jj_3R_MathematicExpressionOperand_294_9_24()
 {
    if (jj_3R_SqlLiteral_379_5_7()) return true;
    return false;
  }

  private boolean jj_3R_SymbolNode_392_5_8()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_SymbolNode_393_9_16()) {
    jj_scanpos = xsp;
    if (jj_3R_SymbolNode_394_9_17()) return true;
    }
    return false;
  }

  private boolean jj_3R_MathematicExpressionOperand_293_5_18()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_MathematicExpressionOperand_294_9_24()) {
    jj_scanpos = xsp;
    if (jj_3R_MathematicExpressionOperand_295_9_25()) {
    jj_scanpos = xsp;
    if (jj_3R_MathematicExpressionOperand_296_9_26()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_MathematicExpressionNode_280_17_20()
 {
    if (jj_3R_MathematicExpressionOperator_344_5_19()) return true;
    if (jj_3R_MathematicExpressionOperand_293_5_18()) return true;
    return false;
  }

  private boolean jj_3R_SqlLiteral_383_7_15()
 {
    if (jj_scan_token(NULL)) return true;
    return false;
  }

  private boolean jj_3R_SqlLiteral_382_7_14()
 {
    if (jj_scan_token(ZERO)) return true;
    return false;
  }

  private boolean jj_3R_SqlLiteral_381_7_13()
 {
    if (jj_scan_token(FLOATING_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_SqlLiteral_380_7_12()
 {
    if (jj_scan_token(DECIMAL_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_SqlLiteral_379_7_11()
 {
    if (jj_scan_token(STRINGVAL)) return true;
    return false;
  }

  private boolean jj_3R_SqlLiteral_379_5_7()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_SqlLiteral_379_7_11()) {
    jj_scanpos = xsp;
    if (jj_3R_SqlLiteral_380_7_12()) {
    jj_scanpos = xsp;
    if (jj_3R_SqlLiteral_381_7_13()) {
    jj_scanpos = xsp;
    if (jj_3R_SqlLiteral_382_7_14()) {
    jj_scanpos = xsp;
    if (jj_3R_SqlLiteral_383_7_15()) return true;
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_SymbolNode_394_84_23()
 {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  /** Generated Token Manager. */
  public ParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[19];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x1f00000,0x2000000,0x1f00000,0x18000,0x7e00,0x0,0x0,0x0,0x0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x600,0x600,0x1,0x1,0x1,0x79820024,0x1800000,0x1,0x79820024,0x79820024,0x0,0x78020024,0x0,0x0,0x0,0x58020020,0x2,0x20000004,0x2,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[5];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new ParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 19; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 19; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new ParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 19; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new ParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 19; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 19; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 19; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[64];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 19; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 64; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 5; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
