/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package com.github.braisdom.jds;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQ = 9;
  /** RegularExpression Id. */
  int GT = 10;
  /** RegularExpression Id. */
  int LT = 11;
  /** RegularExpression Id. */
  int LE = 12;
  /** RegularExpression Id. */
  int GE = 13;
  /** RegularExpression Id. */
  int NE = 14;
  /** RegularExpression Id. */
  int SC_OR = 15;
  /** RegularExpression Id. */
  int SC_AND = 16;
  /** RegularExpression Id. */
  int IN = 17;
  /** RegularExpression Id. */
  int BETWEEN = 18;
  /** RegularExpression Id. */
  int LIKE = 19;
  /** RegularExpression Id. */
  int PLUS = 20;
  /** RegularExpression Id. */
  int MINUS = 21;
  /** RegularExpression Id. */
  int STAR = 22;
  /** RegularExpression Id. */
  int SLASH = 23;
  /** RegularExpression Id. */
  int REM = 24;
  /** RegularExpression Id. */
  int LPAREN = 25;
  /** RegularExpression Id. */
  int RPAREN = 26;
  /** RegularExpression Id. */
  int LBRACE = 27;
  /** RegularExpression Id. */
  int RBRACE = 28;
  /** RegularExpression Id. */
  int LBRACKET = 29;
  /** RegularExpression Id. */
  int RBRACKET = 30;
  /** RegularExpression Id. */
  int SEMICOLON = 31;
  /** RegularExpression Id. */
  int COMMA = 32;
  /** RegularExpression Id. */
  int DOT = 33;
  /** RegularExpression Id. */
  int COLON = 34;
  /** RegularExpression Id. */
  int QUOTE = 35;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE = 36;
  /** RegularExpression Id. */
  int STRINGVAL = 37;
  /** RegularExpression Id. */
  int DBSTRINGVAL = 38;
  /** RegularExpression Id. */
  int BACK_QUOTED_IDENTIFIER = 39;
  /** RegularExpression Id. */
  int IMPORT = 40;
  /** RegularExpression Id. */
  int TYPEDEF = 41;
  /** RegularExpression Id. */
  int DATASET = 42;
  /** RegularExpression Id. */
  int PROJECTION = 43;
  /** RegularExpression Id. */
  int FROM = 44;
  /** RegularExpression Id. */
  int PREDICATE = 45;
  /** RegularExpression Id. */
  int AS = 46;
  /** RegularExpression Id. */
  int RETURN = 47;
  /** RegularExpression Id. */
  int NULL = 48;
  /** RegularExpression Id. */
  int JSYMBOL = 49;
  /** RegularExpression Id. */
  int JPROJECTION = 50;
  /** RegularExpression Id. */
  int JTYPE = 51;
  /** RegularExpression Id. */
  int JPREDICATE = 52;
  /** RegularExpression Id. */
  int JQuery = 53;
  /** RegularExpression Id. */
  int TYPE_NAME = 54;
  /** RegularExpression Id. */
  int IDENTIFIER = 55;
  /** RegularExpression Id. */
  int LETTER = 56;
  /** RegularExpression Id. */
  int DIGIT = 57;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 58;
  /** RegularExpression Id. */
  int FLOATING_LITERAL = 59;
  /** RegularExpression Id. */
  int BOOLEAN_LITERAL = 60;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<token of kind 6>",
    "<token of kind 7>",
    "<token of kind 8>",
    "\"==\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"&=\"",
    "\"~=\"",
    "\"~\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "\"\\\'\"",
    "\"\\\"\"",
    "<STRINGVAL>",
    "<DBSTRINGVAL>",
    "<BACK_QUOTED_IDENTIFIER>",
    "\"import\"",
    "\"typedef\"",
    "\"dataset\"",
    "\"projection\"",
    "\"from\"",
    "\"predicate\"",
    "\"as\"",
    "\"return\"",
    "\"null\"",
    "\"JSymbol\"",
    "\"JProjection\"",
    "\"JType\"",
    "\"JPredicate\"",
    "\"JQuery\"",
    "<TYPE_NAME>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<DECIMAL_LITERAL>",
    "<FLOATING_LITERAL>",
    "<BOOLEAN_LITERAL>",
    "\"#\"",
  };

}
