/* Parser.java */
/* Generated By:JavaCC: Do not edit this line. Parser.java */
package com.github.braisdom.jsql;

import java.util.*;
import com.github.braisdom.jsql.ast.*;

public final class Parser implements ParserConstants {

    public static String unquote(String value, String quote) {
        if (value.startsWith(quote) && (value.endsWith(quote))) {
            return value.substring(1, value.length() - 1);
        }
        return value;
    }

  final public SqlNode SqlNode() throws ParseException {final SqlNode sqlNode = new SqlNode();
    ImportNode importNode;
    DatasetNode datasetNode;
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IMPORT:
      case TYPEDEF:{
        ;
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IMPORT:{
        importNode = ImportNode();
sqlNode.addImportNode(importNode);
        break;
        }
      case TYPEDEF:{
        datasetNode = DatasetNode();
sqlNode.addDatasetNode(datasetNode);
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
{if ("" != null) return sqlNode;}
    throw new Error("Missing return statement in function");
}

  final public ImportNode ImportNode() throws ParseException {ImportNode importNode;
    String importDeclaration;
    jj_consume_token(IMPORT);
    importDeclaration = Name();
importNode = new ImportNode(importDeclaration);
    jj_consume_token(SEMICOLON);
{if ("" != null) return importNode;}
    throw new Error("Missing return statement in function");
}

  final public DatasetNode DatasetNode() throws ParseException {final DatasetNode datasetNode = new DatasetNode();
    FromNode fromNode;
    FormalParameterNode parameter;
    Projectional projectional;
    jj_consume_token(TYPEDEF);
    jj_consume_token(DATASET);
    jj_consume_token(TYPE_NAME);
datasetNode.setName(getToken(0).image);
    jj_consume_token(LPAREN);
    parameter = FormalParameterNode();
datasetNode.addFormalParameter(parameter);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        ;
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        break label_2;
      }
      jj_consume_token(COMMA);
      parameter = FormalParameterNode();
datasetNode.addFormalParameter(parameter);
    }
    jj_consume_token(RPAREN);
    jj_consume_token(LBRACE);
    jj_consume_token(PROJECTION);
    jj_consume_token(LBRACKET);
    Projectional(datasetNode);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        ;
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        break label_3;
      }
      jj_consume_token(COMMA);
      Projectional(datasetNode);
    }
    jj_consume_token(RBRACKET);
    jj_consume_token(COMMA);
    jj_consume_token(FROM);
    jj_consume_token(LPAREN);
    fromNode = FromNode();
datasetNode.addFromNode(fromNode);
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_4;
      }
      jj_consume_token(COMMA);
      fromNode = FromNode();
datasetNode.addFromNode(fromNode);
    }
    jj_consume_token(RPAREN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COMMA:{
      jj_consume_token(COMMA);
      jj_consume_token(PREDICATE);
      jj_consume_token(LPAREN);
      jj_consume_token(RPAREN);
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      ;
    }
    jj_consume_token(RBRACE);
{if ("" != null) return datasetNode;}
    throw new Error("Missing return statement in function");
}

  final public FromNode FromNode() throws ParseException {FromNode fromNode;
    if (jj_2_1(2147483647)) {
      fromNode = SqlFunctionCallNode();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AS:{
        jj_consume_token(AS);
        jj_consume_token(IDENTIFIER);
fromNode.setAlias(token.image);
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        ;
      }
    } else if (jj_2_2(2147483647)) {
      fromNode = SymbolNode();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AS:{
        jj_consume_token(AS);
        jj_consume_token(IDENTIFIER);
fromNode.setAlias(token.image);
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        ;
      }
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return fromNode;}
    throw new Error("Missing return statement in function");
}

  final public FormalParameterNode FormalParameterNode() throws ParseException {String type;
    String name;
    jj_consume_token(TYPE_NAME);
type = getToken(0).image;
    jj_consume_token(IDENTIFIER);
name = getToken(0).image;
{if ("" != null) return new FormalParameterNode(type, name);}
    throw new Error("Missing return statement in function");
}

  final public void Projectional(DatasetNode datasetNode) throws ParseException {Projectional projectional = null;
    Token token;
    if (jj_2_3(2147483647)) {
      projectional = ExpressionNode();
      jj_consume_token(AS);
      token = jj_consume_token(IDENTIFIER);
projectional.setAlias(token.image);
    } else if (jj_2_4(2147483647)) {
      projectional = SymbolNode();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AS:{
        jj_consume_token(AS);
        token = jj_consume_token(IDENTIFIER);
projectional.setAlias(token.image);
        break;
        }
      default:
        jj_la1[8] = jj_gen;
        ;
      }
    } else if (jj_2_5(2147483647)) {
      projectional = SqlLiteral();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AS:{
        jj_consume_token(AS);
        token = jj_consume_token(IDENTIFIER);
projectional.setAlias(token.image);
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        ;
      }
    } else {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case TYPE_NAME:
      case IDENTIFIER:{
        projectional = SqlFunctionCallNode();
        jj_consume_token(AS);
        token = jj_consume_token(IDENTIFIER);
projectional.setAlias(token.image);
        break;
        }
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
datasetNode.addProjectional(projectional);
}

  final public SqlFunctionCallNode SqlFunctionCallNode() throws ParseException {SqlFunctionCallNode sqlFunctionCallNode = new SqlFunctionCallNode();
    SqlFunctionOperand operand;
    if (jj_2_6(2)) {
      jj_consume_token(TYPE_NAME);
sqlFunctionCallNode.setType(token.image);
      jj_consume_token(DOT);
    } else {
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFIER:{
      jj_consume_token(IDENTIFIER);
      break;
      }
    case TYPE_NAME:{
      jj_consume_token(TYPE_NAME);
      break;
      }
    default:
      jj_la1[11] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
sqlFunctionCallNode.setName(getToken(0).image);
    jj_consume_token(LPAREN);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COLON:
    case STRINGVAL:
    case NULL:
    case TYPE_NAME:
    case IDENTIFIER:
    case DECIMAL_LITERAL:
    case FLOATING_LITERAL:
    case 61:{
      operand = SqlFunctionOperand();
sqlFunctionCallNode.addOperands(operand);
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case COMMA:{
          ;
          break;
          }
        default:
          jj_la1[12] = jj_gen;
          break label_5;
        }
        jj_consume_token(COMMA);
        operand = SqlFunctionOperand();
sqlFunctionCallNode.addOperands(operand);
      }
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      ;
    }
    jj_consume_token(RPAREN);
{if ("" != null) return sqlFunctionCallNode;}
    throw new Error("Missing return statement in function");
}

  final public SqlFunctionOperand SqlFunctionOperand() throws ParseException {SqlFunctionOperand operand;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STRINGVAL:
    case NULL:
    case DECIMAL_LITERAL:
    case FLOATING_LITERAL:{
      operand = SqlLiteral();
{if ("" != null) return operand;}
      break;
      }
    case COLON:
    case 61:{
      operand = SymbolNode();
{if ("" != null) return operand;}
      break;
      }
    case TYPE_NAME:
    case IDENTIFIER:{
      operand = SqlFunctionCallNode();
{if ("" != null) return operand;}
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public ExpressionNode ExpressionNode() throws ParseException {ExpressionNode expressionNode = new ExpressionNode();
    ExpressionOperand left;
    String operator;
    ExpressionOperand right;
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LPAREN:
      case COLON:
      case STRINGVAL:
      case NULL:
      case DECIMAL_LITERAL:
      case FLOATING_LITERAL:
      case 61:{
        ;
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        break label_6;
      }
      left = ExpressionOperand();
expressionNode.setLeft(left);
      operator = ExpressionOperator();
expressionNode.setOperator(operator);
      right = ExpressionOperand();
expressionNode.setRight(right);
    }
{if ("" != null) return expressionNode;}
    throw new Error("Missing return statement in function");
}

  final public ExpressionOperand ExpressionOperand() throws ParseException {ExpressionOperand operand = null;
    ExpressionNode expressionNode;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STRINGVAL:
    case NULL:
    case DECIMAL_LITERAL:
    case FLOATING_LITERAL:{
      operand = SqlLiteral();
{if ("" != null) return operand;}
      break;
      }
    case COLON:
    case 61:{
      operand = SymbolNode();
{if ("" != null) return operand;}
      break;
      }
    case LPAREN:{
      jj_consume_token(LPAREN);
      expressionNode = ExpressionNode();
      jj_consume_token(RPAREN);
expressionNode.setEnclosed(true);
            {if ("" != null) return expressionNode;}
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public LogicExpression LogicExpression() throws ParseException {LogicExpression logicExpression = new LogicExpression();
    ExpressionOperand left;
    String operator;
    ExpressionOperand right;
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LPAREN:
      case COLON:
      case STRINGVAL:
      case NULL:
      case DECIMAL_LITERAL:
      case FLOATING_LITERAL:
      case 61:{
        ;
        break;
        }
      default:
        jj_la1[17] = jj_gen;
        break label_7;
      }
      left = ExpressionOperand();
logicExpression.setLeft(left);
      operator = ExpressionOperator();
logicExpression.setOperator(operator);
      right = ExpressionOperand();
logicExpression.setRight(right);
    }
{if ("" != null) return logicExpression;}
    throw new Error("Missing return statement in function");
}

  final public ExpressionOperand LogicExpressionOperand() throws ParseException {ExpressionOperand operand = null;
    LogicExpression logicExpression;
    if (jj_2_7(2147483647)) {
      operand = ExpressionOperand();
{if ("" != null) return operand;}
    } else if (jj_2_8(2147483647)) {
      jj_consume_token(LPAREN);
      logicExpression = LogicExpression();
      jj_consume_token(RPAREN);
logicExpression.setEnclosed(true);
            {if ("" != null) return logicExpression;}
    } else {
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public String ExpressionOperator() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case PLUS:{
      jj_consume_token(PLUS);
{if ("" != null) return token.image;}
      break;
      }
    case MINUS:{
      jj_consume_token(MINUS);
{if ("" != null) return token.image;}
      break;
      }
    case STAR:{
      jj_consume_token(STAR);
{if ("" != null) return token.image;}
      break;
      }
    case SLASH:{
      jj_consume_token(SLASH);
{if ("" != null) return token.image;}
      break;
      }
    case REM:{
      jj_consume_token(REM);
{if ("" != null) return token.image;}
      break;
      }
    case SC_OR:{
      jj_consume_token(SC_OR);
{if ("" != null) return token.image;}
      break;
      }
    case SC_AND:{
      jj_consume_token(SC_AND);
{if ("" != null) return token.image;}
      break;
      }
    case LIKE:{
      jj_consume_token(LIKE);
{if ("" != null) return token.image;}
      break;
      }
    case EQ:
    case GT:
    case LT:
    case LE:
    case GE:
    case NE:{
      CompareOperator();
      break;
      }
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public String LogicOperator() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SC_AND:{
      jj_consume_token(SC_AND);
{if ("" != null) return token.image;}
      break;
      }
    case SC_OR:{
      jj_consume_token(SC_OR);
{if ("" != null) return token.image;}
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public String CompareOperator() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case EQ:{
      jj_consume_token(EQ);
{if ("" != null) return token.image;}
      break;
      }
    case GT:{
      jj_consume_token(GT);
{if ("" != null) return token.image;}
      break;
      }
    case GE:{
      jj_consume_token(GE);
{if ("" != null) return token.image;}
      break;
      }
    case NE:{
      jj_consume_token(NE);
{if ("" != null) return token.image;}
      break;
      }
    case LT:{
      jj_consume_token(LT);
{if ("" != null) return token.image;}
      break;
      }
    case LE:{
      jj_consume_token(LE);
{if ("" != null) return token.image;}
      break;
      }
    default:
      jj_la1[20] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
}

  final public SqlLiteral SqlLiteral() throws ParseException {Object value = null;
    Token token;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case STRINGVAL:{
      token = jj_consume_token(STRINGVAL);
value = token.image;
      break;
      }
    case DECIMAL_LITERAL:{
      token = jj_consume_token(DECIMAL_LITERAL);
value = Integer.parseInt(token.image);
      break;
      }
    case FLOATING_LITERAL:{
      token = jj_consume_token(FLOATING_LITERAL);
value = Float.parseFloat(token.image);
      break;
      }
    case NULL:{
      token = jj_consume_token(NULL);
value = null;
      break;
      }
    default:
      jj_la1[21] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return new SqlLiteral(value);}
    throw new Error("Missing return statement in function");
}

  final public SymbolNode SymbolNode() throws ParseException {SymbolNode symbolNode = new SymbolNode();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case COLON:{
      jj_consume_token(COLON);
      jj_consume_token(IDENTIFIER);
symbolNode.setSymbolName(token.image);
      break;
      }
    case 61:{
      jj_consume_token(61);
      jj_consume_token(IDENTIFIER);
symbolNode.setDatasetName(token.image);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DOT:{
        jj_consume_token(DOT);
        jj_consume_token(IDENTIFIER);
symbolNode.setSymbolName(token.image);
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        ;
      }
      break;
      }
    default:
      jj_la1[23] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
{if ("" != null) return symbolNode;}
    throw new Error("Missing return statement in function");
}

  final public String Name() throws ParseException {List<String> names = new ArrayList();
    jj_consume_token(IDENTIFIER);
names.add(getToken(0).image);
    label_8:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DOT:{
        ;
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        break label_8;
      }
      jj_consume_token(DOT);
      jj_consume_token(IDENTIFIER);
names.add(getToken(0).image);
    }
{if ("" != null) return String.join(".", names.toArray(new String[0]));}
    throw new Error("Missing return statement in function");
}

  private boolean jj_2_1(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_1()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_2_2(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_2()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(1, xla); }
  }

  private boolean jj_2_3(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_3()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(2, xla); }
  }

  private boolean jj_2_4(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_4()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(3, xla); }
  }

  private boolean jj_2_5(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_5()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(4, xla); }
  }

  private boolean jj_2_6(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_6()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(5, xla); }
  }

  private boolean jj_2_7(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_7()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(6, xla); }
  }

  private boolean jj_2_8(int xla)
 {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return (!jj_3_8()); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(7, xla); }
  }

  private boolean jj_3R_ExpressionOperand_276_5_13()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_ExpressionOperand_277_9_23()) {
    jj_scanpos = xsp;
    if (jj_3R_ExpressionOperand_278_9_24()) {
    jj_scanpos = xsp;
    if (jj_3R_ExpressionOperand_279_9_25()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_SqlLiteral_368_7_22()
 {
    if (jj_scan_token(NULL)) return true;
    return false;
  }

  private boolean jj_3R_SqlLiteral_367_7_21()
 {
    if (jj_scan_token(FLOATING_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_SqlLiteral_366_7_20()
 {
    if (jj_scan_token(DECIMAL_LITERAL)) return true;
    return false;
  }

  private boolean jj_3R_SqlLiteral_365_7_19()
 {
    if (jj_scan_token(STRINGVAL)) return true;
    return false;
  }

  private boolean jj_3R_ExpressionNode_263_13_18()
 {
    if (jj_3R_ExpressionOperand_276_5_13()) return true;
    if (jj_3R_ExpressionOperator_324_5_30()) return true;
    if (jj_3R_ExpressionOperand_276_5_13()) return true;
    return false;
  }

  private boolean jj_3R_SqlLiteral_365_5_12()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_SqlLiteral_365_7_19()) {
    jj_scanpos = xsp;
    if (jj_3R_SqlLiteral_366_7_20()) {
    jj_scanpos = xsp;
    if (jj_3R_SqlLiteral_367_7_21()) {
    jj_scanpos = xsp;
    if (jj_3R_SqlLiteral_368_7_22()) return true;
    }
    }
    }
    return false;
  }

  private boolean jj_3R_CompareOperator_356_5_49()
 {
    if (jj_scan_token(LE)) return true;
    return false;
  }

  private boolean jj_3R_ExpressionNode_261_5_11()
 {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_ExpressionNode_263_13_18()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_CompareOperator_355_5_48()
 {
    if (jj_scan_token(LT)) return true;
    return false;
  }

  private boolean jj_3R_CompareOperator_354_5_47()
 {
    if (jj_scan_token(NE)) return true;
    return false;
  }

  private boolean jj_3R_CompareOperator_353_5_46()
 {
    if (jj_scan_token(GE)) return true;
    return false;
  }

  private boolean jj_3R_SymbolNode_379_74_29()
 {
    if (jj_scan_token(DOT)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_CompareOperator_352_5_45()
 {
    if (jj_scan_token(GT)) return true;
    return false;
  }

  private boolean jj_3R_CompareOperator_351_5_44()
 {
    if (jj_scan_token(EQ)) return true;
    return false;
  }

  private boolean jj_3R_CompareOperator_351_5_43()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_CompareOperator_351_5_44()) {
    jj_scanpos = xsp;
    if (jj_3R_CompareOperator_352_5_45()) {
    jj_scanpos = xsp;
    if (jj_3R_CompareOperator_353_5_46()) {
    jj_scanpos = xsp;
    if (jj_3R_CompareOperator_354_5_47()) {
    jj_scanpos = xsp;
    if (jj_3R_CompareOperator_355_5_48()) {
    jj_scanpos = xsp;
    if (jj_3R_CompareOperator_356_5_49()) return true;
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_SqlFunctionOperand_249_9_33()
 {
    if (jj_3R_SqlFunctionCallNode_229_5_9()) return true;
    return false;
  }

  private boolean jj_3R_SqlFunctionOperand_248_9_32()
 {
    if (jj_3R_SymbolNode_377_5_10()) return true;
    return false;
  }

  private boolean jj_3R_SqlFunctionOperand_247_9_31()
 {
    if (jj_3R_SqlLiteral_365_5_12()) return true;
    return false;
  }

  private boolean jj_3R_SqlFunctionCallNode_235_19_28()
 {
    if (jj_scan_token(COMMA)) return true;
    if (jj_3R_SqlFunctionOperand_246_5_27()) return true;
    return false;
  }

  private boolean jj_3R_SqlFunctionCallNode_234_17_15()
 {
    if (jj_3R_SqlFunctionOperand_246_5_27()) return true;
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_SqlFunctionCallNode_235_19_28()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_SqlFunctionOperand_246_5_27()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_SqlFunctionOperand_247_9_31()) {
    jj_scanpos = xsp;
    if (jj_3R_SqlFunctionOperand_248_9_32()) {
    jj_scanpos = xsp;
    if (jj_3R_SqlFunctionOperand_249_9_33()) return true;
    }
    }
    return false;
  }

  private boolean jj_3R_ExpressionOperator_333_9_42()
 {
    if (jj_3R_CompareOperator_351_5_43()) return true;
    return false;
  }

  private boolean jj_3R_ExpressionOperator_332_9_41()
 {
    if (jj_scan_token(LIKE)) return true;
    return false;
  }

  private boolean jj_3R_ExpressionOperator_331_9_40()
 {
    if (jj_scan_token(SC_AND)) return true;
    return false;
  }

  private boolean jj_3R_ExpressionOperator_330_9_39()
 {
    if (jj_scan_token(SC_OR)) return true;
    return false;
  }

  private boolean jj_3R_ExpressionOperator_329_9_38()
 {
    if (jj_scan_token(REM)) return true;
    return false;
  }

  private boolean jj_3R_ExpressionOperator_328_9_37()
 {
    if (jj_scan_token(SLASH)) return true;
    return false;
  }

  private boolean jj_3R_ExpressionOperator_327_9_36()
 {
    if (jj_scan_token(STAR)) return true;
    return false;
  }

  private boolean jj_3_6()
 {
    if (jj_scan_token(TYPE_NAME)) return true;
    if (jj_scan_token(DOT)) return true;
    return false;
  }

  private boolean jj_3R_ExpressionOperator_326_9_35()
 {
    if (jj_scan_token(MINUS)) return true;
    return false;
  }

  private boolean jj_3R_ExpressionOperator_325_9_34()
 {
    if (jj_scan_token(PLUS)) return true;
    return false;
  }

  private boolean jj_3_5()
 {
    if (jj_3R_SqlLiteral_365_5_12()) return true;
    return false;
  }

  private boolean jj_3_4()
 {
    if (jj_3R_SymbolNode_377_5_10()) return true;
    return false;
  }

  private boolean jj_3_8()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_LogicExpression_295_5_14()) return true;
    return false;
  }

  private boolean jj_3_3()
 {
    if (jj_3R_ExpressionNode_261_5_11()) return true;
    if (jj_scan_token(AS)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3_7()
 {
    if (jj_3R_ExpressionOperand_276_5_13()) return true;
    return false;
  }

  private boolean jj_3R_ExpressionOperator_324_5_30()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_ExpressionOperator_325_9_34()) {
    jj_scanpos = xsp;
    if (jj_3R_ExpressionOperator_326_9_35()) {
    jj_scanpos = xsp;
    if (jj_3R_ExpressionOperator_327_9_36()) {
    jj_scanpos = xsp;
    if (jj_3R_ExpressionOperator_328_9_37()) {
    jj_scanpos = xsp;
    if (jj_3R_ExpressionOperator_329_9_38()) {
    jj_scanpos = xsp;
    if (jj_3R_ExpressionOperator_330_9_39()) {
    jj_scanpos = xsp;
    if (jj_3R_ExpressionOperator_331_9_40()) {
    jj_scanpos = xsp;
    if (jj_3R_ExpressionOperator_332_9_41()) {
    jj_scanpos = xsp;
    if (jj_3R_ExpressionOperator_333_9_42()) return true;
    }
    }
    }
    }
    }
    }
    }
    }
    return false;
  }

  private boolean jj_3R_SqlFunctionCallNode_229_5_9()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3_6()) jj_scanpos = xsp;
    xsp = jj_scanpos;
    if (jj_scan_token(55)) {
    jj_scanpos = xsp;
    if (jj_scan_token(54)) return true;
    }
    if (jj_scan_token(LPAREN)) return true;
    xsp = jj_scanpos;
    if (jj_3R_SqlFunctionCallNode_234_17_15()) jj_scanpos = xsp;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_LogicExpression_297_13_26()
 {
    if (jj_3R_ExpressionOperand_276_5_13()) return true;
    if (jj_3R_ExpressionOperator_324_5_30()) return true;
    if (jj_3R_ExpressionOperand_276_5_13()) return true;
    return false;
  }

  private boolean jj_3_2()
 {
    if (jj_3R_SymbolNode_377_5_10()) return true;
    return false;
  }

  private boolean jj_3_1()
 {
    if (jj_3R_SqlFunctionCallNode_229_5_9()) return true;
    return false;
  }

  private boolean jj_3R_LogicExpression_295_5_14()
 {
    Token xsp;
    while (true) {
      xsp = jj_scanpos;
      if (jj_3R_LogicExpression_297_13_26()) { jj_scanpos = xsp; break; }
    }
    return false;
  }

  private boolean jj_3R_SymbolNode_379_9_17()
 {
    if (jj_scan_token(61)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_SymbolNode_379_74_29()) jj_scanpos = xsp;
    return false;
  }

  private boolean jj_3R_SymbolNode_378_9_16()
 {
    if (jj_scan_token(COLON)) return true;
    if (jj_scan_token(IDENTIFIER)) return true;
    return false;
  }

  private boolean jj_3R_ExpressionOperand_279_9_25()
 {
    if (jj_scan_token(LPAREN)) return true;
    if (jj_3R_ExpressionNode_261_5_11()) return true;
    if (jj_scan_token(RPAREN)) return true;
    return false;
  }

  private boolean jj_3R_ExpressionOperand_278_9_24()
 {
    if (jj_3R_SymbolNode_377_5_10()) return true;
    return false;
  }

  private boolean jj_3R_SymbolNode_377_5_10()
 {
    Token xsp;
    xsp = jj_scanpos;
    if (jj_3R_SymbolNode_378_9_16()) {
    jj_scanpos = xsp;
    if (jj_3R_SymbolNode_379_9_17()) return true;
    }
    return false;
  }

  private boolean jj_3R_ExpressionOperand_277_9_23()
 {
    if (jj_3R_SqlLiteral_365_5_12()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public ParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[25];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x2000000,0x2000000,0x2000000,0x1f9fe00,0x18000,0x7e00,0x0,0x0,0x0,0x0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x300,0x300,0x1,0x1,0x1,0x1,0x4000,0x4000,0x4000,0x4000,0xc00000,0xc00000,0x1,0x2cc10024,0x2cc10024,0x2c010024,0x2c010024,0x2c010024,0x0,0x0,0x0,0xc010020,0x2,0x20000004,0x2,};
	}
  final private JJCalls[] jj_2_rtns = new JJCalls[8];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Parser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Parser(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new ParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 25; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 25; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Parser(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new ParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 25; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new ParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 25; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Parser(ParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 25; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(ParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 25; i++) jj_la1[i] = -1;
	 for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   if (++jj_gc > 100) {
		 jj_gc = 0;
		 for (int i = 0; i < jj_2_rtns.length; i++) {
		   JJCalls c = jj_2_rtns[i];
		   while (c != null) {
			 if (c.gen < jj_gen) c.first = null;
			 c = c.next;
		   }
		 }
	   }
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }

  @SuppressWarnings("serial")
  static private final class LookaheadSuccess extends java.lang.Error {
    @Override
    public Throwable fillInStackTrace() {
      return this;
    }
  }
  static private final LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
	 if (jj_scanpos == jj_lastpos) {
	   jj_la--;
	   if (jj_scanpos.next == null) {
		 jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
	   } else {
		 jj_lastpos = jj_scanpos = jj_scanpos.next;
	   }
	 } else {
	   jj_scanpos = jj_scanpos.next;
	 }
	 if (jj_rescan) {
	   int i = 0; Token tok = token;
	   while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
	   if (tok != null) jj_add_error_token(kind, i);
	 }
	 if (jj_scanpos.kind != kind) return true;
	 if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
	 return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
	 if (pos >= 100) {
		return;
	 }

	 if (pos == jj_endpos + 1) {
	   jj_lasttokens[jj_endpos++] = kind;
	 } else if (jj_endpos != 0) {
	   jj_expentry = new int[jj_endpos];

	   for (int i = 0; i < jj_endpos; i++) {
		 jj_expentry[i] = jj_lasttokens[i];
	   }

	   for (int[] oldentry : jj_expentries) {
		 if (oldentry.length == jj_expentry.length) {
		   boolean isMatched = true;

		   for (int i = 0; i < jj_expentry.length; i++) {
			 if (oldentry[i] != jj_expentry[i]) {
			   isMatched = false;
			   break;
			 }

		   }
		   if (isMatched) {
			 jj_expentries.add(jj_expentry);
			 break;
		   }
		 }
	   }

	   if (pos != 0) {
		 jj_lasttokens[(jj_endpos = pos) - 1] = kind;
	   }
	 }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[62];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 25; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 62; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 jj_endpos = 0;
	 jj_rescan_token();
	 jj_add_error_token(0, 0);
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
	 jj_rescan = true;
	 for (int i = 0; i < 8; i++) {
	   try {
		 JJCalls p = jj_2_rtns[i];

		 do {
		   if (p.gen > jj_gen) {
			 jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
			 switch (i) {
			   case 0: jj_3_1(); break;
			   case 1: jj_3_2(); break;
			   case 2: jj_3_3(); break;
			   case 3: jj_3_4(); break;
			   case 4: jj_3_5(); break;
			   case 5: jj_3_6(); break;
			   case 6: jj_3_7(); break;
			   case 7: jj_3_8(); break;
			 }
		   }
		   p = p.next;
		 } while (p != null);

		 } catch(LookaheadSuccess ls) { }
	 }
	 jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
	 JJCalls p = jj_2_rtns[index];
	 while (p.gen > jj_gen) {
	   if (p.next == null) { p = p.next = new JJCalls(); break; }
	   p = p.next;
	 }

	 p.gen = jj_gen + xla - jj_la; 
	 p.first = token;
	 p.arg = xla;
  }

  static final class JJCalls {
	 int gen;
	 Token first;
	 int arg;
	 JJCalls next;
  }

}
